### ISSUE TITLE
for banner yaml data files, combine version and dates

### ISSUE THREAD

**Issue by benlei** [benlei/samsara-web#83]
it currently looks like:

```yaml
  - name: Seele
    versions:
      - 1.0.1
      - 1.4.2
    dates:
      - start: '2023-04-26'
        end: '2023-05-17'
      - start: '2023-10-27'
        end: '2023-11-15'
```

but can probably be improved to:

```yaml
  - name: Seele
    dates:
      - start: '2023-04-26'
        end: '2023-05-17'
        version: 1.0.1
      - start: '2023-10-27'
        end: '2023-11-15'
        version: 1.4.2
```
